helloService:
  replicaCount: 1
  image:
    repository: ""
    tag: "latest"
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 3001
    targetPort: 3001

profileService:
  replicaCount: 1
  image:
    repository: ""
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3002
    targetPort: 3002
  env:
    MONGO_URL: ""
