apiVersion: v1
kind: Service
metadata:
  name: helloservice-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.helloService.service.type }}
  selector:
    app: helloservice
  ports:
    - port: {{ .Values.helloService.service.port }}
      targetPort: {{ .Values.helloService.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: profileservice-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.profileService.service.type }}
  selector:
    app: profileservice
  ports:
    - port: {{ .Values.profileService.service.port }}
      targetPort: {{ .Values.profileService.service.targetPort }}
